apiVersion: v1
kind: Service
metadata:
  name: alertmanager-sybenbolandit
spec:
  selector:
    alertmanager: sybenbolandit
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
