apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: jenkins-project
spec:
  serviceMonitorSelector:
    matchLabels:
      prometheus: jenkins-project
  resources:
    requests:
      memory: 400Mi

