apiVersion: v1
kind: Service
metadata:
  name: "alertmanager-sybrenbolandit"
  labels:
{{ include "kubernetes-monitoring.labels" . | nindent 4 }}
spec:
  selector:
    alertmanager: sybrenbolandit
  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
