apiVersion: v1
kind: Secret
metadata:
  name: "alertmanager-sybrenbolandit"
  labels:
{{ include "kubernetes-monitoring.labels" . | nindent 4 }}
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 1m
    route:
      group_by: ['env', 'job', 'alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1m
      receiver: 'slack'
    receivers:
    - name: slack
      slack_configs:
      - api_url: {{ .Values.prometheus.slack.webhook | quote }}
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        send_resolved: true
        channel: '#{{ .Values.prometheus.slack.alertChannel }}'
        title: {{`'[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.prometheus }} {{ .GroupLabels.job }}'`}}
        text: {{`"<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndocumentation: {{ .CommonAnnotations.documentation }}\n"`}}
