{{- if .Values.fluentd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
{{ include "kubernetes-monitoring.labels" . | nindent 4 }}
data:
  fluent.conf: |
    <source>
      type forward
      bind 0.0.0.0
      port 24224
    </source>

    <match java_log>
      @type elasticsearch
      host elasticsearch-elasticsearch-master
      port 9200
      index_name fluentd
      type_name fluentd
      <buffer>
          @type memory
          flush_thread_count 4
          flush_interval 3s
          chunk_limit_size 5m
          chunk_limit_records 500
      </buffer>
    </match>
{{- end }}
