{{- if .Values.fluentd.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: fluentd
  labels:
{{ include "kubernetes-monitoring.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: fluentd
  minReplicas: {{ .Values.fluentd.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.fluentd.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.fluentd.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
